version: '3.1'

services:
  app:
    image: 5fdcae015707
    container_name: app
    build: docker
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://db:5432/dbKafkaTest
    depends_on:
      - db
  db:
      image: 'postgres'
      container_name: db
      expose:
        - '5432'

      environment:
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_DB=dbKafkaTest
      ports:
        - "5432:5432"
      volumes:
        - ./pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
    driver: local